-- ============================================================================
-- UGC Integrated Dashboard – RLS Smoke‑Test Script
--
-- This script exercises row‑level security policies by impersonating each
-- application role in turn and attempting to read from sensitive tables.
-- It uses Postgres session settings to simulate JWT claims (`request.jwt.claim.sub`
-- and `request.jwt.claim.role`) as generated by Supabase.  For each role, it
-- reports the number of rows returned from key tables.  Use the output to
-- verify that policies permit only authorised access.
--
-- Usage: run this script in psql against your Supabase database.  Ensure
-- that the `profiles` table contains one test user per role (see
-- `seed_dummy_data.sql`).  Adjust the list of tables or roles as needed.
-- ============================================================================

do $$
declare
  u record;
  tbl text;
  tables_to_test constant text[] := ARRAY[
    'audit_logs',
    'imports',
    'marketing_spend',
    'customers',
    'leads',
    'tickets',
    'sla_events',
    'invoices',
    'payments'
  ];
begin
  for u in select user_id, role_name, full_name from profiles loop
    raise notice '*** Testing as role: % (user % – %)', u.role_name, u.user_id, u.full_name;
    -- Set the session JWT claims for this user.  Supabase RLS helpers read
    -- these settings to derive auth.uid() and app_current_role().
    perform set_config('request.jwt.claim.sub', u.user_id::text, true);
    perform set_config('request.jwt.claim.role', u.role_name, true);
    perform set_config('request.jwt.claim.aud', 'authenticated', true);
    -- Optionally set additional claims such as dept_code if your RLS helpers use it
    -- perform set_config('request.jwt.claim.dept_code', (select dept_code from profiles where user_id = u.user_id), true);

    -- Iterate over tables and report row counts
    foreach tbl in array tables_to_test loop
      declare
        row_count bigint;
      begin
        -- Execute the count query dynamically into row_count.  If the table is
        -- protected by RLS and the user has no access, an error or zero rows
        -- will result.  Errors are caught by the exception block.
        execute format('select count(*) from %I', tbl) into row_count;
        raise notice '  %: % rows', tbl, row_count;
      exception when others then
        raise notice '  %: access denied or table not found', tbl;
      end;
    end loop;

    raise notice '';
  end loop;
end $$;

-- End of RLS smoke test script